### PR TITLE
Fix for crash on iOS 15 when scanning OTP over NFC

### LINKED ISSUE #78: [YKFOTPSession] Crash happens on iOS 15 when entering background
Howdy!

We found a recurring crash coming from the YubiKit Framework. The part what is crashed could be found in `YKFOTPSession`, where the `NFCNDEFReaderSession` is used. The problem occurs only on iOS 15, where the `didInvalidateWithError` delegate method called not only once, and the `nfcOTPResponseBlock` is set to nil on the first run , but on the second it will crash because of the `EXEC_BAD_ADDRESS`. Blocks are C level stuff, and don't have the neat `objc_message` nil checking guard over them.

I could reproduce not only in our project, but on a fresh single view application. I think not only our product is affected by this.

1. My idea would be, it does not have to be set to nil every time. In theory the object which holds the Block's pointer should dealloc on its destruction. So could leave on.
2. Or the delegate mechanism would be very nice, and convenient in this situation. It would not harm the pattern.

I can do any direction:

WDYT?

@jensutbult Thanks for your attention.

### PR DESCRIPTION
**Pull request by jensutbult**
Fixes crash on iOS 15 where readerSession:didInvalidateWithError: was called twice when reading a Yubico OTP over NFC. This would happen if the user pressed cancel, sent the app to the background and then opened the app again.

The crash can not be reproduces running our automated tests which is why no new tests that validates the fix has been added. There's however a test project available here: https://github.com/jensutbult/OTP-Crash

Closes #78

### CODE REVIEW

**Comment by leitlia** [comment]
* The fix seems okay to me! ✅ 

* I pulled in my test app like this:
`pod 'YubiKit', :git => 'https://github.com/Yubico/yubikit-ios', :branch => 'jens/ios15-otp-crash'`

* I could not reproduce the crash. 🍏 

Interesting thing, when I tried to validate the crash, then I played around with different solutions, and this line
`if (self.nfcOTPResponseBlock)` still caused crash I think because of the nature of C level blocks. And the explicit nil checking fixed the condition (`if (self.nfcOTPResponseBlock == nil)`). For my understanding the `objc_msgSend` is missing from the Obj-C `Block` mechanism, and that's why it is vulnerable to calling them when they are `nil`.

**Review by AdamVe — APPROVED** [review]

File: YubiKit/YubiKit/Connections/NFCConnection/Sessions/YKFNFCOTPSession.m [hunk 1]
```diff
@@ -74,29 +74,29 @@ - (void)start {
...
     
-    self.nfcSession = nil;
     if ([self shouldIgnoreError: error]) {
         return;
     }
     
     YKFLogNSError(error);
     
-    self.nfcOTPResponseBlock(nil, error);
+    if (self.nfcOTPResponseBlock) self.nfcOTPResponseBlock(nil, error);
```
Comment (dainnilsson) [inline YubiKit/YubiKit/Connections/NFCConnection/Sessions/YKFNFCOTPSession.m:83]: Should we prefer to always use curly braces for if-statements? Is there a "best practice" for this for Obj-C?

**Review by dainnilsson — APPROVED** [review]
